apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: dhruv-nodeclass
spec:
  amiFamily: AL2 # Amazon Linux 2
  #role: "KarpenterNodeRole-EKS-Karpenter" # replace with your karpenter-node-role name
  instanceProfile: "Dhruv-AmazonEKSNodeRole" #Goto karpenter node role arn and find instance profile arn and copy name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "Dhruv-EKS" # replace with your cluster 
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "Dhruv-EKS" # replace with your cluster 
  tags:
    Name: eks-node-spot
