apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: <Cluster_Name>
    #if you don't want to use tag then add subnet id directly
  securityGroupSelector:
    karpenter.sh/discovery: <Cluster_Name>
    #if you don't want to use tag then add SG id directly

