apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  labels:
    type: karpenter
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - id: subnet-0fb0620e17d74b64a 
    - id: subnet-0e97f64c827b8c46c
  securityGroupSelectorTerms:
    - id: sg-0bd15acaa1e9c98d5
  instanceProfile: "eks-72c8a834-4002-a2c4-c474-2e05cdf85e27"
  tags:
    Name: karpenter-node
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
